### ISSUE TITLE
Demonstrate patterns for realistic React apps on ASP.NET

### ISSUE THREAD

**Issue by SteveSandersonMS** [aspnet/NodeServices#15]
Examples:

 * Server-side HTTP requests (i.e., issuing ajax requests during server-side prerendering). Possibly embedding the responses in the resulting HTML and enabling cache priming (would require client-side library code too).
 * Integrating with server-side validation

It is not necessarily true that React developers need or want any suggestions about how to do such things. Looking for community feedback on what (if anything) else ASP.NET should do to improve productivity for React developers.

**Comment by andersekdahl** [comment]
First of all, this repo is awesome!

Here's something we're currently thinking about in a ASP.NET MVC + React application: We have an application which uses React to render the application shell (header, navigation, footer, etc). We want to use React for that to be able to render a different shell depending on which device you use (responsive design is nice, but having the same markup for all devices comes with limitations).

Now, on some pages the entire page is rendered with React but on some pages we want to render with MVC/Razor (because it's convenient, those pages are static, and we get a lot of functionality from out CMS frameworks Razor helpers).

My plans for this has been something like:
```
...
<body>
@Html.RenderReactComponent("App", new { 
    ServerContent = RenderBody(), 
    Navigation = Navigation.GetItems() 
})
</body>
...
```
And the React part would be something like:
```
class App extends React.Component {
  render() {
    return (
      <Layout 
        serverContent={this.props.serverContent} 
        navigation={this.props.navigation} 
      />
    );
  }
}

class Layout extends React.Component {
  render() {
    return (
      <div>
        <header>
          <ul>
            {this.props.navigation.map(item => <li>...</li>)}
          </ul>
        </header>
        <ServerContent serverContent={this.props.serverContent} />
        <footer></footer>
      </div>
    );
  }
}

class ServerContent extends React.Component {
  render() {
    return <div dangerouslySetInnerHTML={{__html: this.props.serverContent}}></div>;
  }
}
```

I don't think this would require you to do anything special (except make it possible to pass an object of `props` to the component to render). 

But here's the tricky part: the call to `RenderBody()` might itself call `@Html.RenderReactComponent()` if any pages contain smaller sections of interactive content where we want to use React. And that's not a problem on it's own, but the thing that makes it difficult is that React won't know that there's an inner call to `ReactDOM.renderToString()` inside of the `ServerContent` passed to `App` since it will just get a big string.

I wouldn't expect this project to magically solve this, just wanted to give you some insight into real world use of ASP.NET + React.

Btw, will this be limited to ASP.NET 5, or will it work with the current ASP.NET?

**Comment by Daniel15** [comment]
> will this be limited to ASP.NET 5, or will it work with the current ASP.NET?

I just learnt about this NodeServices project today. I've got a project called [ReactJS.NET](http://reactjs.net/) that does something similar, and works on both ASP.NET 4 and 5.

**Comment by SteveSandersonMS** [comment]
@andersekdahl Thanks for that info! That will come in useful when planning further React support. And yes, at the moment, the only plan is to build this for ASP.NET 5, but obviously the source is open and I'm sure you could backport it to older ASP.NET if you wanted.

@Daniel15 Cool project! I just tech-reviewed an article last week that uses ReactJS.NET for server-side rendering. I'd be very interested to know if you have views on other React+ASP.NET crossover functionality that people are looking for.

**Comment by llyys** [comment]
It would really hepful to see, how to use server side data loading?
NodeServices/samples/react/ReactGrid/ReactApp/components/PeopleGrid.jsx
that there would be server side rendered data not 
`import { fakeData } from '../data/fakeData.js';`

I don't mean ajax request, but how to inject data via props or globally injected object in server side for PeopleGrid

**Comment by SteveSandersonMS** [comment]
Agreed. I'm working on a much larger and more realistic React example here: https://github.com/aspnet/NodeServices/tree/master/samples/react/MusicStore

I'm in the process of putting in server-side rendering now. This includes fetching data asynchronously on load.

**Comment by gulbanana** [comment]
that sounds like a very useful sample, I look forward to it

**Comment by SteveSandersonMS** [comment]
That sample is now published so I'll close this.

**Comment by gulbanana** [comment]
thanks!
