### ISSUE TITLE
Duplicate identifiers compiler errors

### ISSUE THREAD

**Issue by Bifrost-Design** [aspnet/NodeServices#24]
I get TS 2300 Duplicate identifier compiler errors. with angular2-2.0.0-alpha.53. Is there a fix for these compiler errors? The application runs fine in a browser window if I ignore the compiler errors.

**Comment by SteveSandersonMS** [comment]
Sorry, as per the readme instructions, this package only supports the specific versions of the dependencies it references. In particular it doesn't support newer versions of Angular 2, because the underlying angular2-universal-preview package hasn't yet been updated to support it.

Once the underlying server-side rendering package is updated, I'll update this repo to use it.
