### ISSUE TITLE
Common form validation for client and server

### ISSUE THREAD

**Issue by inongogo** [aspnet/NodeServices#40]
I think one of the most boring things to worry about is form validation. I ran across an asp.net/angular package a while ago and when I saw Steve's great presentation at NDC London, I thought that this functionality might be interesting to incorporate into the AngularServices package. The current package is for Angular 1.x but it might be possible to add simular functionality to Angular 2, which I haven't start looking at yet.

It solves the quite boring and error prune work of having two places to store and handle validation strings and logic. It would be ideal to have all the validation strings and logic (i.e. the logic behind the DataAnnotations attributes) on the server which is then bundled and sent to the client and used there for validation as well.

Unfortunately, I'm not the most experienced developer and just use deveopment to keep my brain from shrinking so I don't have the skills to create a pull request for the functionality (you would probably be att asp.net core 3.0 before I have something to deliver).

The package I'm refering to is on Github at [https://github.com/AngularAgility/AngularAgility]. I think the same functionality would fit in nicely with the pre-render stuff in AngularServices. I don't know what strategy to use for custom validation...I guess the client API would need some extension API or something.

**Comment by SteveSandersonMS** [comment]
Thanks for raising this. It's an interesting question how best to share validation rules in common on both server and client.

It's not something I have a specific proposal about right now, and it's probably out of scope for NodeServices itself (since this is meant to be general infrastructure for combining ASP.NET and Angular/Node/etc) so there's no action to take right now. If you or someone else comes up with a particular design that you think fits into the scope of NodeServices or AngularServices please let us know!
