### ISSUE TITLE
React .tsx typescript files not working

### ISSUE THREAD

**Issue by Strandedpirate** [aspnet/NodeServices#63]
I setup a small app to test NodeServices with React.js, webpack and Typescript but it does not render the _Hello_ component to screen. No client-side errors, the webpack bundle is getting included, but NodeServices isn't sending down the pre-rendered html to the page with Typescript added to the equation.

Is there something special I need to do to get it to render with Typescript in the mix?

**hello.tsx**
```
import React = require("react");

export default class Hello extends React.Component<any, any> {

    render() {
        return <div>Hello world!</div>;
    }
}
```
**index.cshtml**
```
<div id="react-app" asp-prerender-module="ReactApp/UI/Views/hello.tsx"
     asp-prerender-webpack-config="webpack.config.js"></div>

@section scripts {
    <script src="/scripts/app.bundle.js"></script>
}

<h2>Home page!</h2>
```

**Comment by Strandedpirate** [comment]
I was missing this line in **_ViewImports.cshtml** which is why I was getting no details of what the issue was. 

> @addTagHelper "*, Microsoft.AspNet.SpaServices"

After adding it I started seeing this error in VS:

> Microsoft.AspNet.Server.Kestrel: Error: An unhandled exception was thrown by the application.
> System.Exception: Call to Node module failed with error: TypeError: Cannot set property 'props' of undefined
>     at ReactComponent (d:\users\swifty\documents\visual studio 2015\Projects\WebApplication1\src\WebApplication1\node_modules\react\lib\ReactComponent.js:25:14)
>     at Hello (<anonymous>:57:17)
>     at d:\users\swifty\documents\visual studio 2015\Projects\WebApplication1\src\WebApplication1\node_modules\aspnet-prerendering\Prerendering.js:41:13
>     at d:\users\swifty\documents\visual studio 2015\Projects\WebApplication1\src\WebApplication1\node_modules\aspnet-prerendering\node_modules\domain-task\main.js:41:33
>     at bound (domain.js:289:14)
>     at runBound (domain.js:300:12)
>     at Object.exports.run (d:\users\swifty\documents\visual studio 2015\Projects\WebApplication1\src\WebApplication1\node_modules\aspnet-prerendering\node_modules\domain-task\node_modules\domain-context\lib\index.js:90:35)
>     at Object.exports.runInNewDomain (d:\users\swifty\documents\visual studio 2015\Projects\WebApplication1\src\WebApplication1\node_modules\aspnet-prerendering\node_modules\domain-task\node_modules\domain-context\lib\index.js:116:18)
>     at Object.run (d:\users\swifty\documents\visual studio 2015\Projects\WebApplication1\src\WebApplication1\node_modules\aspnet-prerendering\node_modules\domain-task\main.js:33:19)
>     at d:\users\swifty\documents\visual studio 2015\Projects\WebApplication1\src\WebApplication1\node_modules\aspnet-prerendering\Prerendering.js:33:16
>    at Microsoft.AspNet.NodeServices.HttpNodeInstance.<Invoke>d__5`1.MoveNext()

I dumped out the contents of the in-memory webpack output (from LoadViewWebpack.js) and it looks normal. Still attempting to debug the issue.

> (function(e, a) { for(var i in a) e[i] = a[i]; }(exports, /******/ (function(modules) { // webpackBootstrap
> /******/ 	// The module cache
> /******/ 	var installedModules = {};
> /******/
> /******/ 	// The require function
> /******/ 	function __webpack_require__(moduleId) {
> /******/
> /******/ 		// Check if module is in cache
> /******/ 		if(installedModules[moduleId])
> /******/ 			return installedModules[moduleId].exports;
> /******/
> /******/ 		// Create a new module (and put it into the cache)
> /******/ 		var module = installedModules[moduleId] = {
> /******/ 			exports: {},
> /******/ 			id: moduleId,
> /******/ 			loaded: false
> /******/ 		};
> /******/
> /******/ 		// Execute the module function
> /******/ 		modules[moduleId].call(module.exports, module, module.exports, __webpack_require__);
> /******/
> /******/ 		// Flag the module as loaded
> /******/ 		module.loaded = true;
> /******/
> /******/ 		// Return the exports of the module
> /******/ 		return module.exports;
> /******/ 	}
> /******/
> /******/
> /******/ 	// expose the modules object (__webpack_modules__)
> /******/ 	__webpack_require__.m = modules;
> /******/
> /******/ 	// expose the module cache
> /******/ 	__webpack_require__.c = installedModules;
> /******/
> /******/ 	// __webpack_public_path__
> /******/ 	__webpack_require__.p = "";
> /******/
> /******/ 	// Load entry module and return exports
> /******/ 	return __webpack_require__(0);
> /******/ })
> /************************************************************************/
> /******/ ([
> /* 0 */
> /***/ function(module, exports, __webpack_require__) {
> 
> 	"use strict";
> 	var __extends = (this && this.__extends) || function (d, b) {
> 	    for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p];
> 	    function __() { this.constructor = d; }
> 	    d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
> 	};
> 	var React = __webpack_require__(1);
> 	var Hello = (function (_super) {
> 	    __extends(Hello, _super);
> 	    function Hello() {
> 	        _super.apply(this, arguments);
> 	    }
> 	    Hello.prototype.render = function () {
> 	        return React.createElement("div", null, "Hello world!");
> 	    };
> 	    return Hello;
> 	}(React.Component));
> 	Object.defineProperty(exports, "__esModule", { value: true });
> 	exports.default = Hello;
> 
> 
> /***/ },
> /* 1 */
> /***/ function(module, exports) {
> 
> 	module.exports = require("react");
> 
> /***/ }
> /******/ ])));
> //# sourceMappingURL=webpack-output.js.map

**Comment by SteveSandersonMS** [comment]
The `asp-prerender-module` tag helper doesn't know how render React (or Angular, or anything else) components on its own - it's a more general helper for invoking some JavaScript asynchronously and injecting the result into the page.

To use this to render a React component, you'll need to create a little bit of wrapper code that knows how to render React components, and use `asp-prerender-module` to invoke your wrapper code. A while ago we did publish a tag helper that knew about React components specifically, but in realistic apps there are thousands of different ways to set up dependencies for a React app and we can't know exact what your app needs, hence the requirement to supply your own code that knows how to run your React components.

There's an example of how to do this in the project templates. To see it,

    npm install -g yo generator-aspnet-spa
    yo aspnet-spa

... then select the `ReactReduxSpa` option, and run the resulting project. You'll find in that project an example of how to use `asp-prerender-module` to render a React+Redux component. The important code is in the `boot-server.tsx`.

Note that the ReactSpa template (the one without Redux) doesn't include server-side prerendering. Although it would be possible to do server-side React rendering without Redux or a similar pattern, it would be of questionable value since the whole idea with React and isomorphic apps is to be able to transfer server-side execution to the client and continue it seamlessly. It's only possible to transfer server-side state to the client if there's some known central store for that state, which is exactly what the Redux pattern gives you. Without that, a significant chunk of the efficiency gain is lost.
